Add individual testing for testing from System.in
simonpoole/OpeningHoursParser pull request #61
Opened 2021-04-12 09:33 UTC by goodudetheboy

I added an extra form of testing for OpeningHoursParser. Individual testing receives input directly from `System.in` for on-the-fly parsing. To use this test, run `gradle individualTesting` for non-strict mode or `gradle individualTestingStrict` for strict mode. 

For best aesthetic, use `gradle individualTesting--console=plain` for non-strict mode or `gradle individualTestingStrict --console=plain` for strict mode. It removes the progress bar from gradle, and looks better I guess.

2021-04-12 09:42 UTC, goodudetheboy commented
I think this test might be useful if we just want to have a fast look at the parse result from an input string, directly from the terminal.

2021-04-13 10:32 UTC, simonpoole requested changes

2021-04-13 10:32 UTC, simonpoole commented on build.gradle
> +task individualTesting(type: JavaExec) {
Both new tasks should be in the verification group or else they are rather hard to find in UIs that display tasks.

2021-04-13 10:32 UTC, simonpoole commented on build.gradle
> +
Both tasks should be moved below line 126 as 125 and 128 belong to the showDifferencesStrict task

2021-04-13 10:32 UTC, simonpoole commented on src/test/java/ch/poole/openinghoursparser/IndividualTest.java
> +
Lots of gratuitous empty lines here, for what every reason I find them visually extremely annoying between braces, could you remove them, thanks.

2021-04-13 11:12 UTC, goodudetheboy reviewed
Changes added according to your reviews.

2021-04-13 11:55 UTC, simonpoole commented
> 
> 
> Changes added according to your reviews.

Could you rebase on current master (there seems to be some weird commit history that needs cleaning up) and I'll merge.

2021-04-13 11:55 UTC, simonpoole approved these changes

2021-04-13 12:15 UTC, goodudetheboy commented
I have rebased in 51f38a02892aba9e5ee9407e463459dc79955851 and cleaned up some files in a921da4f0fc8073feb813b8ff539873512749f0c, so my current head should be even with master.

2021-04-13 12:23 UTC, merged

2021-04-13 12:24 UTC, simonpoole commented
Thanks!